### ISSUE TITLE
how to create a new dataset ?

### ISSUE THREAD

**Issue by josepqp** [cocodataset/cocoapi#116]
I'm trying to create a new dataset with fish detections. I have the original image and computed mask from them. Images has only one or many fish and background.
As output I need to have json file to use it on deep learning softwares.

Which would be the appropriate way to do it ?

**Comment by alwansm** [comment]
hello, can you elaborate more on the computed mask (the output)? you can write a script to do this.

**Comment by josepqp** [comment]
I already created an script with matlab for this. Thank you @alwansm
