### ISSUE TITLE
Discrepancy in the number of instances

### ISSUE THREAD

**Issue by IssamLaradji** [cocodataset/cocoapi#117]
The website says that there are 886,284 instances:
`COCO 2017 train/val browser (123,287 images, 886,284 instances)`

But when I loaded `instances_train2017.json` and `instances_val2017.json` I get a total of `860001 + 36781 = 896782` instances which is different from the stated number of instances. Is there a reason for this discrepancy ?

Thanks.

**Comment by salihkaragoz** [comment]
@IssamLaradji There is a feature( **iscrowd** == 0 or 1) type in the annotations. There are not clear annotations in the iscrowd bbox.  
And also in the cocodataset website, this was stated.

>  COCO 2017 train/val browser (123,287 images, 886,284 instances). **Crowd labels not shown.** 


Proof
```
import json
data = json.load(open('instances_train2017.json'))
datat_ann = data['annotations']
data = json.load(open('instances_val2017.json'))
datav_ann = data['annotations']
pure_data = []
for ann in datat_ann:
    if ann['iscrowd'] == 0:
        pure_data.append(ann)
print len(pure_data)
# OUTPUT 849949
for ann in datav_ann:
    if ann['iscrowd'] == 0:
        pure_data.append(ann)
print len(pure_data)
# OUTPUT 886284
```
All Instances count              : 896782             
Not iscrowd instance count : 886284

**Comment by IssamLaradji** [comment]
Thanks!
