### ISSUE TITLE
image bbox too large 

### ISSUE THREAD

**Issue by YingweiZhou** [cocodataset/cocoapi#122]
Hi,

I'm scanning the annotated bounding boxes of images but found the in some cases bounding boxes are too large. Is this supposed to be or some potential mistake?

It happens more than once, for example, the following one:
(my codes are based on coco python api. To display bbox, I use python OpenCV and convert the float coordinates, width and height to integer by `np.floor`)

`img Id: 154004 from val2017`
coco_url:http://images.cocodataset.org/val2017/000000154004.jpg

img after displaying the bbox:

Please notice the very left person in red shirt. The bbox which is colored as grey and obviously bbox is too large in this case. Please ignore the bbox at top left corner, which is used to visualize the scale of small objects. The bbox annotation for this object is: `[1, 50, 445, 288]`, 'category_id' is 1. (person) 

![img 154004 from val2017](https://user-images.githubusercontent.com/9106252/36195993-31926d44-1167-11e8-8188-deb5585e066f.png)

**Comment by tylin** [comment]
You visualize an annotation of crowd, which includes a group of people. You can find more details for crowd annotations in 4.1 on the download page.
http://cocodataset.org/#download

**Comment by YingweiZhou** [comment]
@tylin  thanks for your response, I've found the info from the coco paper. Thanks for your help.

**Comment by YingweiZhou** [comment]
@tylin after a short while, I got confused about the crowd area in an image. My question is, in the object detection domain, if one image contains a 'crowd' area (instance amount of the same category >10) and the COCO technical paper mentioned that  "For the purpose of evaluation, areas marked as crowds will be ignored and not affect a detector’s score.". Is that means, when a detector draws a bbox inside the crowd area and not overlapped with the other valid ground truth bboxes, i.e. the background of the crowd area, the detector would not receive penalty or reward for this even it precisely detects the person in red shirt? If so, how did you make that happen during evaluation?

**Comment by handsomefengfeng** [comment]
I‘ve finished the training and I obtained the result.pkl.json.

How can I make the bounding box drawn in the corresponding image?

Could you please inform me which .py can achieve it？

Thanks !!  : )
