### ISSUE TITLE
meaning of "counts" and "size" in "iscrowd: 1" segmentation

### ISSUE THREAD

**Issue by waspinator** [cocodataset/cocoapi#135]
These example were taken from `instances_val2017.json`

When `"iscrowd": 0` segmentation looks like 

```
"segmentation": [
    [
        289.74,
        443.39
    ],
    [
        289.74,
        443.39
    ]
]
```
but when "iscrowd: 1" then  there are additional "counts" and "size" fields. What do they mean?

```
"segmentation": {
    "counts": [
        272,
        2,
        4,
        4
    ],
    "size": [
        240,
        320
    ]
}
```

**Comment by alwansm** [comment]
"iscrowd": 0 if your segmentation based on polygon (object instance) 
"iscrowd": 1 if your segmentation based uncompressed RLE (crowd)
check: https://github.com/facebookresearch/Detectron/issues/100

**Comment by waspinator** [comment]
@alwansm Thanks, its as bit more clear now. I'm still confused on how I convert a compressed RLE to an uncompressed RLE version. 

When I run 

```
a = np.asfortranarray(np.zeros([5, 10])).astype(np.uint8)
mask.encode(a)
```

produces:

```
{'counts': b'b1', 'size': [5, 10]}
```
which is the encoded RLE instead of the list of something that coco expects.

**Comment by waspinator** [comment]
```
def binary_mask_to_rle(binary_mask):
    rle = {'counts': [], 'size': list(binary_mask.shape)}
    counts = rle.get('counts')
    for i, (value, elements) in enumerate(groupby(binary_mask.ravel(order='F'))):
        if i == 0 and value == 1:
            counts.append(0)
        counts.append(len(list(elements)))
    return rle
```

**Comment by andreygizdov** [comment]
> ```
> def binary_mask_to_rle(binary_mask):
>     rle = {'counts': [], 'size': list(binary_mask.shape)}
>     counts = rle.get('counts')
>     for i, (value, elements) in enumerate(groupby(binary_mask.ravel(order='F'))):
>         if i == 0 and value == 1:
>             counts.append(0)
>         counts.append(len(list(elements)))
>     return rle
> ```

`from itertools import groupby`
Is missing from this code snippet
