### ISSUE TITLE
ImportError: No module named pycocotools.coco

### ISSUE THREAD

**Issue by lihua213** [cocodataset/cocoapi#142]
Traceback (most recent call last):
  File "trainer.py", line 5, in <module>
    import coco_loader as coco
  File "/media/lih/ssd_tensorflow-master/coco_loader.py", line 1, in <module>
    from pycocotools.coco import COCO
ImportError: No module named pycocotools.coco

**Comment by Kqiii** [comment]
Have you already successfully run "make" under coco/PythonAPI (or coco/cocoapi-master/PythonAPI, or coco/cocoapi/PythonAPI, which depends on you)?
If not, run it first.
If so,  open your Terminal under the same folder as mentioned, and then run "python setup.py build_ext install" (as written in setup.py), after which you should be able to import pycocotools :)

**Comment by Samjith888** [comment]
Getting error : command cl.exe failed: no such file or directory
