### ISSUE TITLE
Change to 90 categories in detection annotation 2017?

### ISSUE THREAD

**Issue by GeeshangXu** [cocodataset/cocoapi#158]
`instances_train2017.json` and `instances_val2017.json`  have **90 categories** instead of 80 right now, the change seems not notified by coco website.

**Comment by tylin** [comment]
There are always 80 unique category ids.

**Comment by GeeshangXu** [comment]
ah, my bad. Yes, only 80 categories. `COCO.anns`just index to 90 same as category id and have some skipping.
