### ISSUE TITLE
make error under PythonAPI, python.h No such file or directory

### ISSUE THREAD

**Issue by AsyDynamics** [cocodataset/cocoapi#180]
ubunut 16, python 35, cython 0.28-3, already modified makefile to python3, get such error when run make under PythonAPI:

pycocotools/_mask.c:4:20: fatal error: **Python.h**: No such file or directory
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
Makefile:3: recipe for target 'all' failed
make: *** [all] Error 1

**Update**: It turns out that I haven't installed python3-dev. No issue anymore.

**Comment by AsyDynamics** [comment]
It turns out that I haven't installed python3-dev. No issue anymore.

**Comment by salihkaragoz** [comment]
Thanks it worked for me.

I did this

`sudo apt-get install python3.6-dev
`

I didn't catch error but it couldn't install. btw, It let to install with pip without an error.
 So i did also this

`pip3.6 install pycocotools
`

**Comment by csjunxu** [comment]
For my case, I installed python3-dev, but still fails, and I further installed python-dev. No issue anymore.

**Comment by JanisSharma** [comment]
On Ubuntu, I was running Python 3 and I had to install

sudo apt-get install python3-dev
If you want to use a version of Python that is not linked to python3, install the associated python3.x-dev package. For example:

sudo apt-get install python3.5-dev

Find All solutions [Here](https://icetutor.com/question/fatal-error-python-h-no-such-file-or-directory)

**Comment by alvinhu** [comment]
解决了我的问题，谢谢

**Comment by beyhangl** [comment]
@salihkaragoz saved my day. thank you. It's definitely about your dev requirements for your ubuntu.

**Comment by Rajat-Mehta** [comment]
for those who are using some other version of python and facing this issue:
```
sudo apt-get install python3.x-dev
```
replace 'x' with your python version and then do:
```
pip3.x install pycocotools
```

for example, in my case it was:
```
sudo apt-get install python3.8-dev
pip3.8 install Cython
pip3.8 install pycocotools
```

**Comment by monacv** [comment]
In CentOS this will resolve the issue:

`sudo yum install python36-devel`

**Comment by liqi001** [comment]
> In CentOS this will resolve the issue:
> 
> `sudo yum install python36-devel`

oooohhhh! thanks! it help me! 
Successfully built pycocotools!
