### ISSUE TITLE
loading error for panoptic annotations

### ISSUE THREAD

**Issue by iboing** [cocodataset/cocoapi#181]
When loading the newly released panoptic annotations using cocoapi, an error occurs:

from pycocotools.coco import COCO
panoptic = COCO('panoptic_train2017.json')
-----------------------------------------------------------------------------------------------------
loading annotations into memory...
Done (t=0.82s)
creating index...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/pycocotools/coco.py", line 88, in __init__
  File "build/bdist.linux-x86_64/egg/pycocotools/coco.py", line 98, in createIndex
KeyError: 'id'
------------------------------------------------------------------------------------------------------

Did I use a wrong way to load the panoptic annotations ?

**Comment by cao-nv** [comment]
I have the same problems with @iboing 
Is there any instruction to overcome this problems?

**Comment by pisarik** [comment]
Section **6. Tools and Instructions** of [panoptic task describing](http://cocodataset.org/#panoptic-2018) says, that they made another [API](https://github.com/cocodataset/panopticapi) for working with panoptic annotations.

**Comment by iboing** [comment]
Thanks a lot!

**Comment by Loerbri** [comment]
I am experiencing the same issue and it is unclear to me how to make use of the panoptic-api to circumvent this. Could you please elaborate?

**Comment by cao-nv** [comment]
You should not use the COCO api directly for the panoptic segmentation. 
The annotation should be converted to semantic map and instance segmentation annotations first by the scripts [https://github.com/cocodataset/panopticapi](url)

**Comment by hdjang** [comment]
@cao-nv 

Could you be more specific? I tried converting panoptic json file to coco detection format according to their repository. But it required PNG file that corresponds to the panoptic json file. How can I get this PNG file for the panoptic task? It's not clear in the repository how to do this.

**Comment by chunhokennethkong** [comment]
After writing my dataloader, these are the steps I did:

1. I used the [panoptic2detection_coco_format.py](https://github.com/cocodataset/panopticapi/blob/7bb4655548f98f3fedc07bf37e9040a992b054b0/converters/panoptic2detection_coco_format.py) from [cocodataset/panopticapi](https://github.com/cocodataset/panopticapi) to get the non-overlapping instance segmentation labels. Refer to "**From COCO panoptic format to COCO detection formats**" in the [README](https://github.com/cocodataset/panopticapi/blob/7bb4655548f98f3fedc07bf37e9040a992b054b0/CONVERTERS.md) file for more details.
2. Suggested by others from some git issues, I commented out [line 120 ](https://github.com/cocodataset/panopticapi/blob/7bb4655548f98f3fedc07bf37e9040a992b054b0/converters/panoptic2detection_coco_format.py#L120) which gave me an error. 
3. After visualising and checking the label masks, I found that `iscrowd` should be set to `False` when calling `coco.getAnnIds`, at least for my application. Examples of the images that I found non-applicable masks are [260604](https://cocodataset.org/#explore?id=260604), [5620](https://cocodataset.org/#explore?id=5620) and [39322](https://cocodataset.org/#explore?id=39322).

![000000039322](https://user-images.githubusercontent.com/78969238/228539897-b91b6fba-c278-496b-a08e-ec5e4c769686.png)
![000000005620](https://user-images.githubusercontent.com/78969238/228540050-8fc74652-8766-47ff-9a03-5f83e4053100.png)
![000000260604](https://user-images.githubusercontent.com/78969238/228540342-5399ae0c-b4d8-49fb-ad1f-57372c6fffa8.png)

**Comment by thierrypin** [comment]
I still have no idea what all this means. Why would I use a script to convert from panoptic to detection if I want panoptic? The readme files in the repo explain nothing. Whats the format? How do I parse the dataset? There are several converters, but none of them seem useful.
From the start it seemed that the script `combine_semantic_and_instance_predictions` would solve things, but it has a long list of arguments, and some of the files they ask are nowhere to be found in COCO.
