### ISSUE TITLE
Infering BBox labels in the annotations

### ISSUE THREAD

**Issue by preetskhalsa97** [cocodataset/cocoapi#182]
A single annotation looks like this:
[{u'segmentation': [[173.0, 144.38, 178.07, 146.28, 173.64, 165.29, 166.67, 210.92, 169.2, 244.51, 201.52, 246.41, 193.28, 164.66, 186.31, 152.62, 193.91, 137.41, 188.84, 134.87, 178.71, 136.14, 173.64, 142.48]], u'area': 2686.782300000002, u'iscrowd': 0, u'image_id': 22371, u'bbox': [166.67, 134.87, 34.85, 111.54], u'category_id': 32, u'id': 293120}]

Just wanted to confirm if the bbox labels are x,y,w,h in that order.

Thanks a ton!

**Comment by preetskhalsa97** [comment]
Got the answer in the code base, here it is:
x1, x2, y1, y2 = [bb[0], bb[0]+bb[2], bb[1], bb[1]+bb[3]] (fairly unintuitive, right?!)
Due credit to Nirant (https://github.com/NirantK) for pointing me there.
Line 327-https://github.com/cocodataset/cocoapi/blob/master/PythonAPI/pycocotools/coco.py#L327

Shouldn't this be included in the documentation though?

**Comment by harrisonford** [comment]
I was just wondering the same thing, thanks for this input.
