### ISSUE TITLE
How to use COCOEval for the problem of keypoint estimation? Format of results file?

### ISSUE THREAD

**Issue by chi0tzp** [cocodataset/cocoapi#213]
I want to use COCOEval for evaluating my model for human pose estimation. From what I have found out, e.g., in [this](https://github.com/cocodataset/cocoapi/blob/master/PythonAPI/pycocoEvalDemo.ipynb), you need to have your results in a .json file. 

What's exactly the format of this json file for the task of keypoints estimation?

**Comment by lxy5513** [comment]
@chi0tzp 
Do you find solution? 
 For the keypoints, the ordering of labels is [x,y,visible,x,y,visible...],    
`visible`, I don't known  what can I do for when I estimation the keypoints form my own human pose model, because I have can't find the order origin labels.    
thank you in advance
