### ISSUE TITLE
COCO annotations: what do the ids represent?

### ISSUE THREAD

**Issue by ash1995** [cocodataset/cocoapi#244]
```
image{
"id" : int,  <---------------------------------------------
"width" : int, 
"height" : int,
 "file_name" : str, 
"license" : int,
 "flickr_url" : str, 
"coco_url" : str, 
"date_captured" : datetime,
}

annotation{
"id" : int,  <-----------------------------------------
"image_id" : int,    <--------------------------------------
"category_id" : int, 
"segmentation" : RLE or [polygon], 
"area" : float, 
"bbox" : [x,y,width,height], 
"iscrowd" : 0 or 1,
}
```
In total there are 3 keys having the name id - 
1. id in annotation dictionary, 
2. image_id in annotation dictionary
3. id in image dictionary.

I can understand that the annotation id and annotation image_id is a unique id for the annotation and the image respectively. But then what is the id in the image dictionary?

So for example, if I had 2000 images in my dataset and there are a total of 5000 annotated objects in those images (the dataset). There will be 2000 unique image ids and 5000 unique annotation ids.

But how does the id in the images dictionary come into play? I initially thought that the image id in the annotation dictionary and the id in the image dictionary are the same but I recently found that it's not.

Does someone know what exactly these ids represent and how are they related to each other?

**Comment by ashnair1** [comment]
My bad. The id in the image dictionary is in fact the same as the image_id in the annotation dictionary.

So if I had an image with 2 annotated objects, the id values would be as follows:

In annotation dictionary:
{
[........
image_id = img1
id = 1]
[......
image_id = img1
id = 2]
}

In image dictionary
[id = img1,
.........] 
 
Edit: Fixed img id as pointed out by @priteshgohil

**Comment by priteshgohil** [comment]
An image with 2 annotated objects, shouldn't it be following?

{
[........
image_id = img1
id = 1]
[......
image_id = img1
id = 2]
}

In image dictionary
[id = img1,
.........]

**Comment by ashnair1** [comment]
@priteshgohil  You're right. Fixed comment.
