### ISSUE TITLE
what's the reason

### ISSUE THREAD

**Issue by jiangkeng123** [cocodataset/cocoapi#251]
python setup.py build_ext --inplace
running build_ext
cythoning pycocotools/_mask.pyx to pycocotools/_mask.c
building 'pycocotools._mask' extension
creating build
creating build/common
creating build/temp.linux-x86_64-2.7
creating build/temp.linux-x86_64-2.7/pycocotools
gcc -pthread -B /home/jiang/anaconda3/envs/Python27/compiler_compat -Wl,--sysroot=/ -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/jiang/anaconda3/envs/Python27/lib/python2.7/site-packages/numpy/core/include -I../common -I/home/jiang/anaconda3/envs/Python27/include/python2.7 -c ../common/maskApi.c -o build/temp.linux-x86_64-2.7/../common/maskApi.o -Wno-cpp -Wno-unused-function -std=c99
../common/maskApi.c: In function ‘rleToBbox’:
../common/maskApi.c:141:31: warning: ‘xp’ may be used uninitialized in this function [-Wmaybe-uninitialized]
       if(j%2==0) xp=x; else if(xp<x) { ys=0; ye=h-1; }
                               ^
gcc -pthread -B /home/jiang/anaconda3/envs/Python27/compiler_compat -Wl,--sysroot=/ -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/jiang/anaconda3/envs/Python27/lib/python2.7/site-packages/numpy/core/include -I../common -I/home/jiang/anaconda3/envs/Python27/include/python2.7 -c pycocotools/_mask.c -o build/temp.linux-x86_64-2.7/pycocotools/_mask.o -Wno-cpp -Wno-unused-function -std=c99
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/pycocotools
gcc -pthread -shared -B /home/jiang/anaconda3/envs/Python27/compiler_compat -L/home/jiang/anaconda3/envs/Python27/lib -Wl,-rpath=/home/jiang/anaconda3/envs/Python27/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-2.7/../common/maskApi.o build/temp.linux-x86_64-2.7/pycocotools/_mask.o -L/home/jiang/anaconda3/envs/Python27/lib -lpython2.7 -o build/lib.linux-x86_64-2.7/pycocotools/_mask.so
copying build/lib.linux-x86_64-2.7/pycocotools/_mask.so -> pycocotools
rm -rf build

**Comment by varunagrawal** [comment]
There doesn't seem to be anything wrong here. What exactly is the issue you're facing?

**Comment by varunagrawal** [comment]
Are you building and running with the same version of python? It seems like you are compiling with one version of python and running the code with another version.

**Comment by Harshad1409** [comment]
you are right Varun. Thanks Issue is fixed now.
