### ISSUE TITLE
How to use COCOEval? Format of results file?

### ISSUE THREAD

**Issue by houweidong** [cocodataset/cocoapi#253]
I want to evaluate my model on the coco dataset, but I can't find the json file format for the result.

**Comment by okanlv** [comment]
It is given in http://cocodataset.org/#format-results

**Comment by niazahamd89** [comment]
hi @houweidong @okanlv i am facing the same issue please let me clear, I train the model on both train and evaluate coco 2017 dataset as a result my model generates output in .ckpt format which i prior use for estimation of pose but i am confuse how i can get the result.json file for evaluation of model to know the AP or AR. is the model generates this file by self?
