### ISSUE TITLE
Can anyone provide a descrition of how to use the cocoeval object to calculate F1?

### ISSUE THREAD

**Issue by RaymondKirk** [cocodataset/cocoapi#266]
I've tried saving the TP/FP/TN/FN values in the main accumulate loop but the value of F1 is much less than the one shown if I plot the precision array against the recall threshold array, so i'm assuming I don't save the correct values.

I cannot find any documentation on how to use the dt/gt/Imgs. I tried calculating F1 from the Average Precision and Average Recall values output to the console but I also fear that using this value is wrong due to using averaged values of both precision and recall from different operations.

I know this repo isn't maintained much but any guidance would be appriciated + helpful!

**Comment by SenneRoot** [comment]
hello, 
I wonder if you solved this issue and if so how you did it? I also struggle with this issue and would like to calculate the F1 score.

**Comment by LaCandela** [comment]
Hey, I'm also intersested in this, anyone has any idea? It seems to me that only the best recall is stored after accumulate() so I cannot calculate the F1 score unless I hack the cocoapi....

**Comment by LaCandela** [comment]
Hi! I am also interested in this. It seems to me that not all recall value is stored after calling accumulate() only the best, so I cannot calculate the F1 score without hacking the cocoapi. Are you planning to modify the api so that one can have the recall values as well?

**Comment by bhuvanofc** [comment]
@RaymondKirk Were you able to calculate the F1 score? If so please do share
