### ISSUE TITLE
Error installing cocoapi ../common/maskApi.c:15:34: error: invalid conversion from ‘void*’ to ‘uint* {aka unsigned int*}’ [-fpermissive]

### ISSUE THREAD

**Issue by pkishan1990** [cocodataset/cocoapi#274]
Operating System: Ubuntu 16.04
(base)Precision-Tower-3620:~/cocoapi/PythonAPI$ make install
# install pycocotools to the Python site-packages
python setup.py build_ext install
running build_ext
skipping 'pycocotools/_mask.c' Cython extension (up-to-date)
building 'pycocotools._mask' extension
gcc -pthread -B /home/computer-science-department/anaconda2/compiler_compat -Wl,--sysroot=/ -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/computer-science-department/anaconda2/lib/python2.7/site-packages/numpy/core/include -I../common -I/home/computer-science-department/anaconda2/include/python2.7 -c ../common/maskApi.c -o build/temp.linux-x86_64-2.7/../common/maskApi.o -Wno-cpp -Wno-unused-function -std=c99
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
cc1plus: warning: command line option ‘-std=c99’ is valid for C/ObjC but not for C++
../common/maskApi.c: In function ‘void rleInit(RLE*, siz, siz, siz, uint*)’:
../common/maskApi.c:15:34: error: invalid conversion from ‘void*’ to ‘uint* {aka unsigned int*}’ [-fpermissive]
   R->h=h; R->w=w; R->m=m; R->cnts=(m==0)?0:malloc(sizeof(uint)*m);
                                  ^
../common/maskApi.c: In function ‘void rleEncode(RLE*, const byte*, siz, siz, siz)’:
../common/maskApi.c:34:16: error: invalid conversion from ‘void*’ to ‘uint* {aka unsigned int*}’ [-fpermissive]
   cnts = malloc(sizeof(uint)*(a+1));
                ^
../common/maskApi.c: In function ‘void rleMerge(const RLE*, RLE*, siz, int)’:
../common/maskApi.c:54:16: error: invalid conversion from ‘void*’ to ‘uint* {aka unsigned int*}’ [-fpermissive]
   cnts = malloc(sizeof(uint)*(h*w+1));
                ^
../common/maskApi.c: In function ‘void rleIou(RLE*, RLE*, siz, siz, byte*, double*)’:
../common/maskApi.c:79:12: error: invalid conversion from ‘void*’ to ‘BB {aka double*}’ [-fpermissive]
   db=malloc(sizeof(double)*m*4); rleToBbox(dt,db,m);
            ^
../common/maskApi.c:80:12: error: invalid conversion from ‘void*’ to ‘BB {aka double*}’ [-fpermissive]
   gb=malloc(sizeof(double)*n*4); rleToBbox(gt,gb,n);
            ^
../common/maskApi.c: In function ‘void rleFrPoly(RLE*, const double*, siz, siz, siz)’:
../common/maskApi.c:165:11: error: invalid conversion from ‘void*’ to ‘int*’ [-fpermissive]
   x=malloc(sizeof(int)*(k+1)); y=malloc(sizeof(int)*(k+1));
           ^
../common/maskApi.c:165:40: error: invalid conversion from ‘void*’ to ‘int*’ [-fpermissive]
   x=malloc(sizeof(int)*(k+1)); y=malloc(sizeof(int)*(k+1));
                                        ^
../common/maskApi.c:169:11: error: invalid conversion from ‘void*’ to ‘int*’ [-fpermissive]
   u=malloc(sizeof(int)*m); v=malloc(sizeof(int)*m); m=0;
           ^
../common/maskApi.c:169:36: error: invalid conversion from ‘void*’ to ‘int*’ [-fpermissive]
   u=malloc(sizeof(int)*m); v=malloc(sizeof(int)*m); m=0;
                                    ^
../common/maskApi.c:184:11: error: invalid conversion from ‘void*’ to ‘int*’ [-fpermissive]
   x=malloc(sizeof(int)*k); y=malloc(sizeof(int)*k);
           ^
../common/maskApi.c:184:36: error: invalid conversion from ‘void*’ to ‘int*’ [-fpermissive]
   x=malloc(sizeof(int)*k); y=malloc(sizeof(int)*k);
                                    ^
../common/maskApi.c:193:16: error: invalid conversion from ‘void*’ to ‘uint* {aka unsigned int*}’ [-fpermissive]
   k=m; a=malloc(sizeof(uint)*(k+1));
                ^
../common/maskApi.c:198:11: error: invalid conversion from ‘void*’ to ‘uint* {aka unsigned int*}’ [-fpermissive]
   b=malloc(sizeof(uint)*k); j=m=0; b[m++]=a[j++];
           ^
../common/maskApi.c: In function ‘char* rleToString(const RLE*)’:
../common/maskApi.c:207:17: error: invalid conversion from ‘void*’ to ‘char*’ [-fpermissive]
   char *s=malloc(sizeof(char)*m*6);
                 ^
../common/maskApi.c: In function ‘void rleFrString(RLE*, char*, siz, siz)’:
../common/maskApi.c:220:33: error: invalid conversion from ‘void*’ to ‘uint* {aka unsigned int*}’ [-fpermissive]
   while( s[m] ) m++; cnts=malloc(sizeof(uint)*m); m=0;
                                 ^
error: command 'gcc' failed with exit status 1
Makefile:7: recipe for target 'install' failed
make: *** [install] Error 1

**Comment by pkishan1990** [comment]
Solved by uninstalling gcc4.9 and gcc5 and sudo apt-get install gcc

**Comment by DAA233** [comment]
With gcc 4.9, I solved this error by adding a `-fpermissive` argument in `setup.py`:

```python
from setuptools import setup, Extension
import numpy as np

# To compile and install locally run "python setup.py build_ext --inplace"
# To install library to Python site-packages run "python setup.py build_ext install"

ext_modules = [
    Extension(
        'pycocotools._mask',
        sources=['../common/maskApi.c', 'pycocotools/_mask.pyx'],
        include_dirs = [np.get_include(), '../common'],
        extra_compile_args=['-Wno-cpp', '-Wno-unused-function', '-std=c99', '-fpermissive'],
    )
]

setup(
    name='pycocotools',
    packages=['pycocotools'],
    package_dir = {'pycocotools': 'pycocotools'},
    install_requires=[
        'setuptools>=18.0',
        'cython>=0.27.3',
        'matplotlib>=2.1.0'
    ],
    version='2.0',
    ext_modules= ext_modules
)
```
