### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by sauravsolanki** [cocodataset/cocoapi#308]
I tried every possible way suggested here. nothing works. What to do, Please help me.
python setup.py build_ext --inplace
running build_ext
skipping 'pycocotools/_mask.c' Cython extension (up-to-date)
building 'pycocotools._mask' extension
creating build
creating build/common
creating build/temp.linux-x86_64-3.7
creating build/temp.linux-x86_64-3.7/pycocotools
gcc -pthread -B /home/saurav/anaconda3/envs/cv/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/saurav/anaconda3/envs/cv/lib/python3.7/site-packages/numpy/core/include -I../common -I/home/saurav/anaconda3/envs/cv/include/python3.7m -c ../common/maskApi.c -o build/temp.linux-x86_64-3.7/../common/maskApi.o -Wno-cpp -Wno-unused-function -std=c99
../common/maskApi.c: In function ‘rleDecode’:
../common/maskApi.c:46:7: warning: this ‘for’ clause does not guard... [-Wmisleading-indentation]
       for( k=0; k<R[i].cnts[j]; k++ ) *(M++)=v; v=!v; }}
       ^~~
../common/maskApi.c:46:49: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘for’
       for( k=0; k<R[i].cnts[j]; k++ ) *(M++)=v; v=!v; }}
                                                 ^
../common/maskApi.c: In function ‘rleFrPoly’:
../common/maskApi.c:166:3: warning: this ‘for’ clause does not guard... [-Wmisleading-indentation]
   for(j=0; j<k; j++) x[j]=(int)(scale*xy[j*2+0]+.5); x[k]=x[0];
   ^~~
../common/maskApi.c:166:54: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘for’
   for(j=0; j<k; j++) x[j]=(int)(scale*xy[j*2+0]+.5); x[k]=x[0];
                                                      ^
../common/maskApi.c:167:3: warning: this ‘for’ clause does not guard... [-Wmisleading-indentation]
   for(j=0; j<k; j++) y[j]=(int)(scale*xy[j*2+1]+.5); y[k]=y[0];
   ^~~
../common/maskApi.c:167:54: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘for’
   for(j=0; j<k; j++) y[j]=(int)(scale*xy[j*2+1]+.5); y[k]=y[0];
                                                      ^
../common/maskApi.c: In function ‘rleToString’:
../common/maskApi.c:212:7: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
       if(more) c |= 0x20; c+=48; s[p++]=c;
       ^~
../common/maskApi.c:212:27: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
       if(more) c |= 0x20; c+=48; s[p++]=c;
                           ^
../common/maskApi.c: In function ‘rleFrString’:
../common/maskApi.c:220:3: warning: this ‘while’ clause does not guard... [-Wmisleading-indentation]
   while( s[m] ) m++; cnts=malloc(sizeof(uint)*m); m=0;
   ^~~~~
../common/maskApi.c:220:22: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘while’
   while( s[m] ) m++; cnts=malloc(sizeof(uint)*m); m=0;
                      ^~~~
../common/maskApi.c:228:5: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
     if(m>2) x+=(long) cnts[m-2]; cnts[m++]=(uint) x;
     ^~
../common/maskApi.c:228:34: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
     if(m>2) x+=(long) cnts[m-2]; cnts[m++]=(uint) x;
                                  ^~~~
../common/maskApi.c: In function ‘rleToBbox’:
../common/maskApi.c:141:31: warning: ‘xp’ may be used uninitialized in this function [-Wmaybe-uninitialized]
       if(j%2==0) xp=x; else if(xp<x) { ys=0; ye=h-1; }
                               ^
gcc -pthread -B /home/saurav/anaconda3/envs/cv/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/saurav/anaconda3/envs/cv/lib/python3.7/site-packages/numpy/core/include -I../common -I/home/saurav/anaconda3/envs/cv/include/python3.7m -c pycocotools/_mask.c -o build/temp.linux-x86_64-3.7/pycocotools/_mask.o -Wno-cpp -Wno-unused-function -std=c99
creating build/lib.linux-x86_64-3.7
creating build/lib.linux-x86_64-3.7/pycocotools
gcc -pthread -shared -B /home/saurav/anaconda3/envs/cv/compiler_compat -L/home/saurav/anaconda3/envs/cv/lib -Wl,-rpath=/home/saurav/anaconda3/envs/cv/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.7/../common/maskApi.o build/temp.linux-x86_64-3.7/pycocotools/_mask.o -o build/lib.linux-x86_64-3.7/pycocotools/_mask.cpython-37m-x86_64-linux-gnu.so
copying build/lib.linux-x86_64-3.7/pycocotools/_mask.cpython-37m-x86_64-linux-gnu.so -> pycocotools
rm -rf build
(cv)  ⚙ saurav@concave  ~/Documents/Computer Vision Work/cocoapi/PythonAPI  BAAAAADD

**Comment by sauravsolanki** [comment]
This solved my problem:
Just check all dependencies version installed.
**environment.yml**

name: <ENV NAME>
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - blas=1.0=openblas
  - ca-certificates=2019.5.15=1
  - certifi=2019.6.16=py37_1
  - cycler=0.10.0=py_1
  - cython=0.29.13=py37he1b5a44_0
  - dbus=1.13.6=he372182_0
  - expat=2.2.5=he1b5a44_1003
  - fontconfig=2.13.1=he4413a7_1000
  - freetype=2.10.0=he983fc9_1
  - gettext=0.19.8.1=hc5be6a0_1002
  - glib=2.58.3=h6f030ca_1002
  - gst-plugins-base=1.14.5=h0935bb2_0
  - gstreamer=1.14.5=h36ae1b5_0
  - icu=58.2=hf484d3e_1000
  - jpeg=9c=h14c3975_1001
  - kiwisolver=1.1.0=py37hc9558a2_0
  - libblas=3.8.0=12_openblas
  - libcblas=3.8.0=12_openblas
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libiconv=1.15=h516909a_1005
  - liblapack=3.8.0=12_openblas
  - libopenblas=0.3.7=h6e990d7_0
  - libpng=1.6.37=hed695b0_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libuuid=2.32.1=h14c3975_1000
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.9=h13577e0_2
  - matplotlib=3.1.0=py37h5429711_0
  - ncurses=6.1=he6710b0_1
  - numpy=1.16.4=py37h99e49ec_0
  - numpy-base=1.16.4=py37h2f8d375_0
  - openssl=1.1.1c=h7b6447c_1
  - pcre=8.41=hf484d3e_1003
  - pip=19.1.1=py37_0
  - pthread-stubs=0.4=h14c3975_1001
  - pycocotools=2.0.0=py37h14c3975_1000
  - pyparsing=2.4.2=py_0
  - pyqt=5.9.2=py37hcca6a23_2
  - python=3.7.4=h265db76_1
  - python-dateutil=2.8.0=py_0
  - pytz=2019.2=py_0
  - qt=5.9.7=h52cfd70_2
  - readline=7.0=h7b6447c_5
  - setuptools=41.0.1=py37_0
  - sip=4.19.8=py37hf484d3e_1000
  - six=1.12.0=py37_1000
  - sqlite=3.29.0=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - tornado=6.0.3=py37h516909a_0
  - wheel=0.33.4=py37_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - attrs==19.1.0
    - backcall==0.1.0
    - bleach==3.1.0
    - decorator==4.4.0
    - defusedxml==0.6.0
    - entrypoints==0.3
    - imageio==2.5.0
    - ipykernel==5.1.2
    - ipython==7.7.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.5.1
    - jedi==0.15.1
    - jinja2==2.10.1
    - jsonschema==3.0.2
    - jupyter==1.0.0
    - jupyter-client==5.3.1
    - jupyter-console==6.0.0
    - jupyter-core==4.5.0
    - markupsafe==1.1.1
    - mistune==0.8.4
    - nbconvert==5.6.0
    - nbformat==4.4.0
    - networkx==2.3
    - notebook==6.0.0
    - opencv-python==4.1.0.25
    - pandas==0.25.0
    - pandocfilters==1.4.2
    - parso==0.5.1
    - pexpect==4.7.0
    - pickleshare==0.7.5
    - pillow==6.1.0
    - prometheus-client==0.7.1
    - prompt-toolkit==2.0.9
    - ptyprocess==0.6.0
    - pygments==2.4.2
    - pyrsistent==0.15.4
    - pywavelets==1.0.3
    - pyzmq==18.1.0
    - qtconsole==4.5.2
    - scikit-image==0.15.0
    - scipy==1.3.1
    - send2trash==1.5.0
    - terminado==0.8.2
    - testpath==0.4.2
    - traitlets==4.3.2
    - wcwidth==0.1.7
    - webencodings==0.5.1
    - widgetsnbextension==3.5.1
prefix: <CONDA ENV PATH>
-----------------------------
in my case, it is **cv** is env name
<ENV NAME> -- > cv
<CONDA ENV PATH> --> /home/saurav/anaconda3/envs/cv
-----------------------------
--------
If error is xp is not defined,then
in line 292,put 
xp = 0;

Hope, This will solve your problem.

**Comment by sauravsolanki** [comment]
Please check the dependencies is your virtual env not in parent env. This may lead to make error.

**Comment by TemiLee** [comment]
@sauravsolanki  
`If error is xp is not defined,then
in line 292,put
xp = 0;`
in which file should this code add to ?

**Comment by sauravsolanki** [comment]
Ya Thank you. I did it. I have solved this issues.

**Comment by sauravsolanki** [comment]
See this: ../common/maskApi.c:141:31: warning: ‘xp’ may be used uninitialized in this function [-Wmaybe-uninitialized]
# add this in common/maskApi.c in line 292
# xp = 0
if(j%2==0) xp=x; else if(xp<x) { ys=0; ye=h-1; }

**Comment by TemiLee** [comment]
@sauravsolanki  but the file  common/maskApi.c have 231 lines in total.
 can i add 'xp=0' before the if(j%2==0) xp=x; else if(xp<x) { ys=0; ye=h-1; }?
