### ISSUE TITLE
How to save an image with annotations overlaid on top of it?

### ISSUE THREAD

**Issue by AndreaPi** [cocodataset/cocoapi#312]
Suppose I have in `image_data` valid metadata for an image from a custom COCO dataset. I
can display the image and the annotation with

```
import skimage.io as io
import matplotlib.pyplot as plt

image_directory ='such_and_such/'

image = io.imread(image_directory + image_data['file_name'])
plt.imshow(image); plt.axis('off')
pylab.rcParams['figure.figsize'] = (8.0, 10.0)
annotation_ids = example_coco.getAnnIds(imgIds=image_data['id'], catIds=category_ids, iscrowd=None)
annotations = example_coco.loadAnns(annotation_ids)
example_coco.showAnns(annotations)
```

At this point, I'll be able to see annotations overlaid over the image. However, I want to save the image with the annotations overlaid on top of it. How can I do that? I tried

```
io.imsave(fname="test.png", arr=image)
```

But it doesn't work. It just saves the original image, without any annotation.

**Comment by casoetan** [comment]
Did you get this fixed

**Comment by jpainam** [comment]
Hi, having the same problem, did you manage to save the image.

**Comment by vscv** [comment]
This is because 'coco.showAnns' is drawing on 'plt' instead of modifying the image.

`plt.savefig('path/to/filename.jpg', bbox_inches='tight', pad_inches=0)`

ps. bbox_inches='tight', pad_inches=0, just used to remove white border of saved image.
