### ISSUE TITLE
How to change cocoapi to set threshold for small/medium/large AP evaluation?

### ISSUE THREAD

**Issue by chen3718** [cocodataset/cocoapi#325]
I am testing with my own dectection dataset with COCO format, after I set self.areaRng in setDetParams in cocoeval.py. the APm and APl become -1. But I am quite sure many boxes are large than the medium threshold. 
Is there anything else I need to change?

 self.areaRng = [[0 ** 2, 1e5 ** 2], [0 ** 2, 32 ** 2], [32 ** 2, 96 ** 2], [96 ** 2, 1e5 ** 2]]
is the size in original image, right?

**Comment by chen3718** [comment]
while I set self.areaRng = [[0 ** 2, 1e5 ** 2], [0 ** 2, 32 ** 2], [32 ** 2, 96 ** 2], [96 ** 2, 1e5 ** 2]]
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.673
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.945
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.798
 **Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.710
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.000**

while I set self.areaRng = [[0 ** 2, 1e5 ** 2], **[0 ** 2, 1 ** 2], [0 ** 2, 2 ** 2]**, [2 ** 2, 1e5 ** 2]]
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.673
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.945
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.798
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.711
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.711
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = -1.000

**Comment by chen3718** [comment]
my original image is 1920*1080 while most object is between [45*15] and [150*50]

**Comment by ashnair1** [comment]
Setting self.areaRng =  [[0 ** 2, 1e5 ** 2], [0 ** 2, 1 ** 2], [0 ** 2, 2 ** 2], [2 ** 2, 1e5 ** 2]] implies you're including small objects in the medium range as well. Not sure if that's what you want. Ultimately the area ranges are determined via the object area distribution in your test set. 

So calculate the object areas in your test, divide the entire range such that all your 'small' objects fall under a particular value (S) and all your 'large' objects fall over a particular value (L). The range between S and L will be your medium range.

**Comment by chen3718** [comment]
@ashnair1 thanks for reply! 
The overlap is a mistake. I got the same results after change it to no overlap.
 The main problem is that the large object seems have not been counted, do you know what is the  32 ** 2 unit here? pixel number?

**Comment by ashnair1** [comment]
It's **object area**. 
```
[0 ** 2, 32 ** 2],     # small - objects that have area between 0 sq pixels and 32*32 (1024) sq pixels 
[32 ** 2, 96 ** 2],   # medium - objects that have area between 32*32 sq pixels and 96*96 (9216) sq pixels
[96 ** 2, 1e5 ** 2]]  #  large - objects that have area between 96*96 sq pixels and 1e5*1e5 (1e10) sq pixels
```

**Comment by chen3718** [comment]
just add following line in your script, before that make sure your json file have correct **area** value
`    coco_eval = COCOeval(cocoGt=coco, cocoDt=detections, iouType='bbox')
    coco_eval.params.image_ids = image_ids
    **coco_eval.params.areaRng = [[0 ** 2, 1e5 ** 2], [0 ** 2, 20 ** 2], [20 ** 2, 30 ** 2], [30 ** 2, 1e5 ** 2]]**
    coco_eval.evaluate()
    coco_eval.accumulate()
    coco_eval.summarize()
`
