### ISSUE TITLE
bug in annToRLE

### ISSUE THREAD

**Issue by jinfagang** [cocodataset/cocoapi#348]
```
{'id': 21075, 'image_id': 1002, 'category_id': 1, 'segmentation': [[1250, 510, 1250, 515], [1220, 509, 1220, 511, 1219, 512, 1218, 512, 1217, 513, 1215, 513, 1215, 515, 1217, 517, 1227, 517, 1228, 518, 1230, 516, 1230, 510, 1226, 514, 1225, 514, 1224, 513, 1223, 513, 1220, 510], [1229, 504, 1228, 505, 1228, 506, 1227, 507, 1226, 507, 1225, 508, 1224, 508, 1224, 509, 1225, 509, 1228, 506, 1229, 506, 1230, 505], [1243, 502, 1243, 504, 1241, 506, 1240, 506, 1239, 505, 1238, 505, 1236, 507, 1236, 511, 1237, 512, 1240, 512, 1242, 510, 1243, 510, 1245, 508, 1245, 503, 1244, 502], [1250, 500, 1250, 501, 1251, 500], [1244, 497, 1243, 498, 1244, 499]], 'bbox': [1215, 496, 37, 23], 'iscrowd': 0, 'area': 1.0}

```

I have a ann like above, but can not using:

```
rle = cocoGt.annToRLE(a)
mask = maskUtils.decode(rle)
```

Which got error:

```
    rle = cocoGt.annToRLE(a)
  File "/usr/local/lib/python3.6/dist-packages/pycocotools/coco.py", line 416, in annToRLE
    rles = maskUtils.frPyObjects(segm, h, w)
  File "pycocotools/_mask.pyx", line 293, in pycocotools._mask.frPyObjects
TypeError: Argument 'bb' has incorrect type (expected numpy.ndarray, got list)
```

I can not found anything wrong in the format?

**Comment by gabrielibagon** [comment]
The source of the issue is described in this comment: https://github.com/cocodataset/cocoapi/issues/139#issuecomment-447613074

> This happens if mask length for an annotation = 4, when it gets interpreted differently - as a bbox. See here: https://github.com/cocodataset/cocoapi/blob/master/PythonAPI/pycocotools/_mask.pyx#L292
> 
> In the example above - this segmentation annotation probably triggered this error [355, 205, 355, 208]

**Solution**:
Modify your annotation so that no segmentations have length=4. You can do this by appending the last element to the list again, making it length=5. Something like this:

```
segmentations = []
for seg in annotation['segmentation']:
    if len(seg) == 4:
        seg.append(seg[-1])
    segmentations.append(seg)
annotation['segmentation'] = segmentations
```

This is a bit of a hacky workaround, but it avoids the above error. Ideally, pycocotools should find a more robust way to determine segmentations vs bboxes.

**Comment by jinfagang** [comment]
thanks, i get it.

**Comment by hana9090** [comment]
@gabrielibagon where should I add this modification? I am using[ this dataset](https://patrickwasp.com/wp-content/uploads/2018/04/shapes_train_dataset.zip) as coco formate
from this [link](https://patrickwasp.com/create-your-own-coco-style-dataset/) 

I got this error: 

`File "pycocotools/_mask.pyx", line 293, in pycocotools._mask.frPyObjects
TypeError: Argument 'bb' has incorrect type (expected numpy.ndarray, got list)`

**Comment by gabrielibagon** [comment]
@hana9090 This can be done in a separate block of code or a separate script. 

After you have created your annotations, iterate through them and modify the annotations as described in [my comment above](https://github.com/cocodataset/cocoapi/issues/348#issuecomment-562978725).

I haven't used the pycococreator tool that you've linked, but you can load each annotation, modify it, and resave the annotation.

Something like this (pseudocode):
```
# iterate through annotations
for filename in annotation_filenames:

    # load annotation
    annotation = load_annotation(filename)
    
    # modify annotation (my code from above)
    segmentations = []
    for seg in annotation['segmentation']:
        if len(seg) == 4:
            seg.append(seg[-1])
        segmentations.append(seg)
    annotation['segmentation'] = segmentations

    # save modified annotation
    save_annotation(annotation)
```

I hope this helps.

**Comment by hana9090** [comment]
@gabrielibagon it is really help! Thank you so much :)

**Comment by hana9090** [comment]
@gabrielibagon But that won't affect the training and testing data?

**Comment by gabrielibagon** [comment]
@hana9090 No, I don't think so. The segmentations are a compressed format to describe the masks using a series of points. My modification duplicates one of the points, but the resulting mask should be the same. The training is done using the masks, not the segmentations.
