### ISSUE TITLE
NameError: name 'unicode' is not defined when passing numpy array to loadRes instead of json file using python3

### ISSUE THREAD

**Issue by rra94** [cocodataset/cocoapi#366]
the loadRes file should be able to take a  numpy array of (Nx7) as well but there is  the condition:

if type(resFile) == str or (PYTHON_VERSION == 2 and type(resFile) == unicode):

so both python version AND unicode need to be checked. However, as unicode does not exist in python3 we get an error 

a possible fix is is

str = uniocode when python version is 2

**Comment by tgandor** [comment]
The version in `master` already has it fixed. But it would be nice if you published a new version on PyPI.
