### ISSUE TITLE
Unable to download the pascal voc annotation referred in datasets/data/readme.md

### ISSUE THREAD

**Issue by palver7** [cocodataset/cocoapi#370]
Hi,  I followed this link: https://storage.googleapis.com/coco-dataset/external/PASCAL_VOC.zip 
as told  in https://github.com/facebookresearch/Detectron/blob/master/detectron/datasets/data/README.md 
to download the pascal voc annotations in COCO format. but when I linked to it  I received an error message on the web page: 

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Access denied.</Message>
<Details>
Anonymous caller does not have storage.objects.get access to coco-dataset/external/PASCAL_VOC.zip.
</Details>
</Error>

I have tried using wget as explained in an answer to issue #216 but I also get this error: 
HTTP request sent, awaiting response... 403 Forbidden
2020-02-05 21:18:56 ERROR 403: Forbidden.

Anyone experiencing the same problem? 
Any help will be much appreciated.

**Comment by TWDH** [comment]
I have the same problem, have you downloaded it successfully?

**Comment by palver7** [comment]
Still no success.

**Comment by TWDH** [comment]
> Still no success.

Hi, you have any alternative link to download it? I tried to create the annotation myself but got weird error

**Comment by tienthegainz** [comment]
Same issue

**Comment by TWDH** [comment]
I have created it on my own and works fine. Here is the link:https://drive.google.com/drive/folders/1KtfQovwqE1XD4yh0aBtShrlRnhrDhLrX?usp=sharing

**Comment by palver7** [comment]
@TWDH Thanks a lot! I have used your annotations in my work and they worked fine.

**Comment by palver7** [comment]
Because TWDH has created another repository for the JSON files of pascal_voc this solves the issue and I am closing it.

**Comment by dongjuns** [comment]
guys, just use like this.   

```
wget --no-check-certificate 'https://docs.google.com/uc?export=download&id=1QsfNxxLD7IecYX2fcDgVnRaTexENYzVX' -O pascal_train2007.json
wget --no-check-certificate 'https://docs.google.com/uc?export=download&id=1u1CPR-kQnzLEtJp3BoELc8LMOLRJ127H' -O pascal_val2007.json
```
