### ISSUE TITLE
string image ids and anns id

### ISSUE THREAD

**Issue by sedflix** [cocodataset/cocoapi#373]
https://github.com/cocodataset/cocoapi/blob/e140a084d678eacd18e85a9d8cfa45d1d5911db9/PythonAPI/pycocotools/coco.py#L66-L67

`_isArrayLike` is used to replaces `int` with `List[int]` as several places. Due to this, pycocotools offers a special support when we have `int`  image or annotation ids. 

Example function:
https://github.com/cocodataset/cocoapi/blob/e140a084d678eacd18e85a9d8cfa45d1d5911db9/PythonAPI/pycocotools/coco.py#L222-L231

Since python strings are like arrays, at the current moment we will get a `KeyError` if try to use something like `loadImgs("string_id")`. 

I think it would be cool to have similar support for string ids for non-trivial cases.

**Comment by miquel-espinosa** [comment]
I agree. It would be nice to support "string" image ids.
@sedflix did you solve it?
