### ISSUE TITLE
How to evaluate partial of the coco dataset?

### ISSUE THREAD

**Issue by glentimemaker** [cocodataset/cocoapi#375]
Hi,
My question is how I can evaluate only 10 classes and a small amount of images per class?
I tried but it's a little bit complicated to modify the code, can anyone find a easy way of changing the number of class and the number of images per class to evaluate? Thank you!

**Comment by ruthvik92** [comment]
Hey, did you figure this out? @glentimemaker

**Comment by liuxinyuk** [comment]
```
cocoGt = COCO(gt_path)  
cocoPd = cocoGt.loadRes(res_path)
catIds = cocoGt.getCatIds(catNms=['your class'])   

cocoEval = COCOeval(cocoGt, cocoDt, annType)
cocoEval.params.catIds = catIds # class specified
cocoEval.evaluate()
cocoEval.accumulate()
cocoEval.summarize()
```
