### ISSUE TITLE
Can you upload Python API to PyPI?

### ISSUE THREAD

**Issue by acgtyrant** [cocodataset/cocoapi#53]
So that I can install it via pip. Thank you!

**Comment by wookayin** [comment]
Good. But it seems that we might need to re-structure the entire project repository.

The following is a workaround to install `pycocotools` via pip:
```
pip install -e 'git+https://github.com/pdollar/coco.git#egg=pycocotools&subdirectory=PythonAPI'
```

**Comment by acgtyrant** [comment]
@wookayin Amazing url!

**Comment by ahundt** [comment]
I'd really appreciate if this could be done!

Wouldn't dramatic restructuring not be required other than setup.py being placed in the top level directory?

**Comment by jacsmith21** [comment]
Pycocotools seems to be [available on PyPi](https://pypi.org/project/pycocotools/) now:
```
pip install pycocotools
```
