### ISSUE TITLE
Compiling MatlabAPI WIndows

### ISSUE THREAD

**Issue by priyanka-chaudhary** [cocodataset/cocoapi#88]
I am trying to compile the MatlabAPI on windows. 
I got the gason.h file from https://github.com/mahyarnajibi/coco/tree/master/MatlabAPI/private
When I compile mex gasonMex.cpp I get a lot of error from gason.h 

![gason_error](https://user-images.githubusercontent.com/16559928/33076998-c75d680a-cece-11e7-973e-f1ed12b21240.JPG)

Did someone also faced a similar issue or know how to resolve it?
Thank you!

**Comment by nightrome** [comment]
You might want to try to "Compile with C++11 support (-std=c++11 flag for gcc/clang)" [https://github.com/vivkin/gason](https://github.com/vivkin/gason)

**Comment by priyanka-chaudhary** [comment]
I tried that mex -v COMPFLAGS="$COMPFLAGS -std=c++11 -Wall" -largeArrayDims gasonMex.cpp too but still errors. 
Thanks anyway!

**Comment by mingloo** [comment]
The following commands (mentioned in [gasonMex.m](https://github.com/cocodataset/cocoapi/blob/727b546dd9fa4e4bb113213c98a3925829fac0bf/MatlabAPI/gason.m#L21)) could successfully compile the `gasonMex.mexw64`:
`cd MatlabAPI`
`mex('CXXFLAGS=\$CXXFLAGS -std=c++11 -Wall','-largeArrayDims',...
     'private/gasonMex.cpp','../common/gason.cpp',...
     '-I../common/','-outdir','private');`

Note: I've Matlab 2017b and Visual Studio 2017 installed.
