### ISSUE TITLE
ERROR: compiler_compat/ld: cannot find -lpthread -lc

### ISSUE THREAD

**Issue by q-gao** [cocodataset/cocoapi#94]
I am trying to build cocoapi's **PythonAPI** on **Ubuntu 14.04** with **Anaconda Python 3.6**, but got the following messages. I also tried Python 3.5, but get the same error messages
```sh
/local/mnt/workspace/Apps/anaconda2/envs/py35/compiler_compat/ld: cannot find -lpthread
/local/mnt/workspace/Apps/anaconda2/envs/py36/compiler_compat/ld: cannot find -lc
collect2: error: ld returned 1 exit status
error: command 'gcc' failed with exit status 1
```

**Comment by q-gao** [comment]
This is an Anaconda issue. I fixed it by adding the following to `ext_modules` definition in `setup.py`:
```python
extra_link_args=['-L/usr/lib/x86_64-linux-gnu/']
```

**Comment by rebeen** [comment]
@q-gao , please how to add this line to setup.py how can we find this file ?

**Comment by rebeen** [comment]
how to solve this problem please
![anaconda](https://user-images.githubusercontent.com/1238516/35417491-ecbf274a-022d-11e8-9616-d6d8f99020a5.png)

**Comment by jsinge97** [comment]
You can find `setup.py` in the directory of `$COCOAPI/PythonAPI`. There will be an extension where you can add an additional entry with the following:

`extra_link_args=['-L/usr/lib/x86_64-linux-gnu/']`

**Comment by SpaceMeerkat** [comment]
I'm getting a similar issue as the OP where my error statement is:
`/home/user/anaconda3/compiler_compat/ld: cannot find -lgsl`
But in the compile code I have the line:
`libs_dirs = ['/opt/local/lib','/usr/lib/x86_64-linux-gnu/']`
So I'm not sure what more can be done..?
