### ISSUE TITLE
json.loads(annotations/val2014) ERROR

### ISSUE THREAD

**Issue by RyanCodes44** [cocodataset/cocoapi#98]
Are people able to load the .json file for the validation annotations? I keep getting the error: 

ValueError: Invalid control character at: line 1 column 244752 (char 244751). 
This occurs at line 6 in the 'pycocoEvalDemo' ( ---> cocoGt=COCO(annFile))
which goes to line 84 in 'pycocotools/coco.py' (---> dataset=json.load(open(annotation_file,'r')))

Sorry if this is a noob question, but I am a noob and have no idea how to fix this. I have tried adding 'strict=False' when loading the .json file but to no success. Anyone? Thank you!

**Comment by hosang** [comment]
Did you check which character is at that location? I never encountered that problem. Maybe the downloaded file is corrupt? Did you edit it in any way?

**Comment by RyanCodes44** [comment]
I did not edit it, but looking at the file, it may be corrupt. Has a lot of odd characters and some are highlighted in red. I will try another file and see if I have any other issues. I was unable to check the exact character because the .json file kept freezing.

**Comment by RyanCodes44** [comment]
Yes I apologize the file was corrupted.
